manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/petejohanson
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: zephyr-main-rp2040-playground
      import: app/west.yml
  self:
    path: config
